import React,{useEffect,useState}from"react";import ReactDOM from"react-dom/client";import{addDoc,collection,deleteDoc,doc,getDoc,onSnapshot,serverTimestamp,setDoc,updateDoc}from"firebase/firestore";import{db}from"./firebase";import"./styles.css";
const makeCode=()=>{const a="ABCDEFGHJKLMNPQRSTUVWXYZ23456789";return Array.from({length:5},()=>a[Math.floor(Math.random()*a.length)]).join("")};
function App(){const[screen,setScreen]=useState("home"),[roomCode,setRoomCode]=useState(""),[join,setJoin]=useState(""),[host,setHost]=useState(false),[room,setRoom]=useState(null),[items,setItems]=useState([]),[text,setText]=useState(""),[msg,setMsg]=useState(""),[rot,setRot]=useState(0),[selected,setSelected]=useState(null);
useEffect(()=>{if(!roomCode)return;const a=onSnapshot(doc(db,"rooms",roomCode),s=>setRoom(s.data()));const b=onSnapshot(collection(db,"rooms",roomCode,"entries"),s=>setItems(s.docs.map(d=>({id:d.id,...d.data()}))));return()=>{a();b()}},[roomCode]);
async function create(){let c=makeCode();while((await getDoc(doc(db,"rooms",c))).exists())c=makeCode();await setDoc(doc(db,"rooms",c),{status:"collecting",createdAt:serverTimestamp()});setRoomCode(c);setHost(true);setScreen("room")}
async function enter(){const c=join.trim().toUpperCase();const s=await getDoc(doc(db,"rooms",c));if(!s.exists()){setMsg("Такой комнаты нет");return}setRoomCode(c);setHost(false);setScreen("room")}
async function add(){if(!text.trim())return setMsg("Напиши текст");await addDoc(collection(db,"rooms",roomCode,"entries"),{text:text.trim(),createdAt:serverTimestamp()});setText("");setMsg("Добавлено анонимно")}
async function start(){if(items.length<2)return setMsg("Нужно минимум 2 записи");await updateDoc(doc(db,"rooms",roomCode),{status:"playing"})}
function spin(){if(items.length<2)return;const i=Math.floor(Math.random()*items.length);setSelected(null);setRot(r=>r+2160+Math.random()*720);setTimeout(()=>setSelected(items[i]),4100)}
async function remove(){if(!selected)return;await deleteDoc(doc(db,"rooms",roomCode,"entries",selected.id));setSelected(null)}
if(screen==="home")return <main className="app"><h1>💋 Колесо сплетен</h1><div className="card"><button className="primary" onClick={create}>Создать комнату</button><input value={join} onChange={e=>setJoin(e.target.value)} maxLength="5" placeholder="Код комнаты"/><button onClick={enter}>Войти</button>{msg&&<div className="notice">{msg}</div>}</div></main>;
const playing=room?.status==="playing";return <main className="app"><div className="code">{roomCode}</div>{!playing?<div className="card"><textarea value={text} onChange={e=>setText(e.target.value)} placeholder="Сплетня, вопрос или задание"/><button className="primary" onClick={add}>Добавить анонимно</button><p>Записей: {items.length}</p>{host&&<button onClick={start}>Начать игру</button>}{msg&&<div className="notice">{msg}</div>}</div>:<div className="card"><div className="wheel" style={{transform:`rotate(${rot}deg)`}}>SPIN</div><button className="primary" onClick={spin}>Крутить</button>{selected&&<div className="result">{selected.text}{host&&<div><button onClick={remove}>Удалить выпавшее</button></div>}</div>}</div>}</main>}
ReactDOM.createRoot(document.getElementById("root")).render(<App/>);
